version: '3.1'

services:
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env

volumes:
  db_data:
